[0m12:17:54.765102 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7da2ab103710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7da2aac95970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7da2ab103380>]}


============================== 12:17:54.769752 | 4ee17571-857a-4b8f-b68a-269e10430f47 ==============================
[0m12:17:54.769752 [info ] [MainThread]: Running with dbt=1.9.2
[0m12:17:54.770530 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/codespace/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init proj_poc', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:17:54.780193 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/home/codespace/.dbt')}
[0m12:17:54.780755 [info ] [MainThread]: Creating dbt configuration folder at 
[0m12:17:54.782143 [debug] [MainThread]: Starter project path: /usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/include/starter_project
[0m12:17:54.786688 [info ] [MainThread]: 
Your new dbt project "proj_poc" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:17:54.787422 [info ] [MainThread]: Setting up your profile.
[0m12:19:04.410852 [info ] [MainThread]: Profile proj_poc written to /home/codespace/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m12:19:04.413876 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 69.704636, "process_in_blocks": "26000", "process_kernel_time": 0.272083, "process_mem_max_rss": "90972", "process_out_blocks": "136", "process_user_time": 1.387476}
[0m12:19:04.415324 [debug] [MainThread]: Command `dbt init` succeeded at 12:19:04.415117 after 69.71 seconds
[0m12:19:04.416068 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7da2aaba3980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7da2aa664950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7da2aae40260>]}
[0m12:19:04.416620 [debug] [MainThread]: Flushing usage events
[0m12:19:05.316069 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:19:28.157686 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x729803a4ff20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72980401b980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x729803cacbc0>]}


============================== 12:19:28.162560 | 70c7bdf3-4233-462c-9b57-4fed1120bad6 ==============================
[0m12:19:28.162560 [info ] [MainThread]: Running with dbt=1.9.2
[0m12:19:28.163567 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/codespace/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:19:28.178070 [info ] [MainThread]: dbt version: 1.9.2
[0m12:19:28.178903 [info ] [MainThread]: python version: 3.12.1
[0m12:19:28.179602 [info ] [MainThread]: python path: /usr/local/python/3.12.1/bin/python3
[0m12:19:28.180419 [info ] [MainThread]: os info: Linux-6.5.0-1025-azure-x86_64-with-glibc2.31
[0m12:19:28.290660 [info ] [MainThread]: Using profiles dir at /home/codespace/.dbt
[0m12:19:28.291400 [info ] [MainThread]: Using profiles.yml file at /home/codespace/.dbt/profiles.yml
[0m12:19:28.291969 [info ] [MainThread]: Using dbt_project.yml file at /workspaces/dremio_dbt/dbt_project.yml
[0m12:19:28.292708 [info ] [MainThread]: adapter type: dremio
[0m12:19:28.293212 [info ] [MainThread]: adapter version: 1.8.1
[0m12:19:28.293725 [info ] [MainThread]: Configuration:
[0m12:19:28.294207 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m12:19:28.294738 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m12:19:28.295225 [info ] [MainThread]: Required dependencies:
[0m12:19:28.295794 [debug] [MainThread]: Executing "git --help"
[0m12:19:28.298870 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m12:19:28.299409 [debug] [MainThread]: STDERR: "b''"
[0m12:19:28.299844 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m12:19:28.300349 [info ] [MainThread]: Connection:
[0m12:19:28.300861 [info ] [MainThread]:   cloud_host: None
[0m12:19:28.301328 [info ] [MainThread]:   cloud_project_id: None
[0m12:19:28.301797 [info ] [MainThread]:   software_host: localhost
[0m12:19:28.302261 [info ] [MainThread]:   port: 9047
[0m12:19:28.302834 [info ] [MainThread]:   use_ssl: False
[0m12:19:28.303320 [info ] [MainThread]:   environment: None
[0m12:19:28.303794 [info ] [MainThread]:   UID: jatinmarwaha
[0m12:19:28.304261 [info ] [MainThread]:   root_path: no_schema
[0m12:19:28.304801 [info ] [MainThread]:   datalake: $scratch
[0m12:19:28.305277 [info ] [MainThread]:   database: @jatinmarwaha
[0m12:19:28.305824 [info ] [MainThread]:   schema: no_schema
[0m12:19:28.306679 [info ] [MainThread]:   user: jatinmarwaha
[0m12:19:28.307168 [info ] [MainThread]:   username: jatinmarwaha
[0m12:19:28.307648 [info ] [MainThread]:   object_storage_source: $scratch
[0m12:19:28.308136 [info ] [MainThread]:   object_storage_path: no_schema
[0m12:19:28.308637 [info ] [MainThread]:   dremio_space: @jatinmarwaha
[0m12:19:28.309104 [info ] [MainThread]:   dremio_space_folder: no_schema
[0m12:19:28.309794 [info ] [MainThread]: Registered adapter: dremio=1.8.1
[0m12:19:28.443055 [debug] [MainThread]: Acquiring new dremio connection 'debug'
[0m12:19:28.443708 [debug] [MainThread]: dremio adapter: Using dremio connection "debug". fetch=False
[0m12:19:28.444191 [debug] [MainThread]: dremio adapter: On debug: select 1 as id
[0m12:19:28.444626 [debug] [MainThread]: Opening a new connection, currently in state init
[0m12:19:28.480894 [debug] [MainThread]: dremio adapter: Error running SQL: select 1 as id
[0m12:19:28.481525 [debug] [MainThread]: On debug: No close available on handle
[0m12:19:28.482052 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m12:19:28.482820 [info ] [MainThread]: [31m2 checks failed:[0m
[0m12:19:28.483389 [info ] [MainThread]: Project loading failed for the following reason:
 project path </workspaces/dremio_dbt/dbt_project.yml> not found

[0m12:19:28.484002 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  Unauthorized:: (401 Client Error: Unauthorized for url: http://localhost:9047/apiv2/login): ({"errorMessage":"Login failed: Invalid username or password, user jatinmarwaha","moreInfo":"","stackTrace":[]})

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m12:19:28.485811 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.3855041, "process_in_blocks": "1664", "process_kernel_time": 0.247925, "process_mem_max_rss": "92204", "process_out_blocks": "24", "process_user_time": 1.503548}
[0m12:19:28.486533 [debug] [MainThread]: Command `dbt debug` failed at 12:19:28.486416 after 0.39 seconds
[0m12:19:28.487047 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m12:19:28.487521 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x729803b2a1e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x729802eaf7d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72980424e120>]}
[0m12:19:28.488256 [debug] [MainThread]: Flushing usage events
[0m12:19:29.238891 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m03:44:22.276344 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ee922a7baa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ee9230e4c50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ee9228791c0>]}


============================== 03:44:22.281229 | 934fe233-7ce0-420a-8476-68a645642155 ==============================
[0m03:44:22.281229 [info ] [MainThread]: Running with dbt=1.9.2
[0m03:44:22.282082 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/codespace/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run -s stg_orders', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m03:44:22.282718 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/dremio_dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m03:44:22.285621 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.073695324, "process_in_blocks": "864", "process_kernel_time": 0.227586, "process_mem_max_rss": "85060", "process_out_blocks": "16", "process_user_time": 1.341563}
[0m03:44:22.286596 [debug] [MainThread]: Command `dbt run` failed at 03:44:22.286446 after 0.07 seconds
[0m03:44:22.287363 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ee922543f80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ee922e8a240>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ee922cfe7b0>]}
[0m03:44:22.288129 [debug] [MainThread]: Flushing usage events
[0m03:44:23.239036 [debug] [MainThread]: An error was encountered while trying to flush usage events
